### PR TITLE
Add Hystrix support to migrator

### PR DESCRIPTION
**Pull request by dcrissman**
Note: Hystrix is non-optional at this time.

### CODE REVIEW

**Comment by jewzaam** [comment]
Missing configuration.  Default is isolation of THREAD with a timeout of 1000 msec.  We might want to swap to SEMAPHORE for this client and increase concurrent requests from the default of 10.

**Comment by jewzaam** [comment]
https://github.com/Netflix/Hystrix/wiki/Configuration#CommandExecution

**Comment by dcrissman** [comment]
@jewzaam would those be changes for the puppet layer?

**Comment by jewzaam** [comment]
For migrator I would say just bundle it as a resource for now.  We can refactor it out later.  We're not using hystrix to limit concurrent jobs so just set the concurrent requests to something high.  We want hystrix in this case for the ease of getting metrics.

We could put this as part of the client/hystrix module.  Not sure the implications to making changes to configs for clients.  Standalone apps like migrator could pass a command line arg.  For jboss deployments having many clients in a container it gets harder.

**Comment by dcrissman** [comment]
@jewzaam changes made, ready for review

**Comment by dcrissman** [comment]
Still doing some testing... please hold off on review. Thanks.

**Comment by dcrissman** [comment]
@jewzaam This is ready for review.

**Pull request merged**
