### PR TITLE
Trying to fix intermittent facade test failures

### PR DESCRIPTION
**Pull request by paterczm**
For some reason java8 builds take much longer than java7 builds (e.g. https://travis-ci.org/lightblue-platform/lightblue-migrator/builds/142510528). This could be responsible for test failures.

### CODE REVIEW

**Comment by bserdar** [comment]
How about using Breakpoint? it is in migrator package.

**Comment by paterczm** [comment]
The java7 build is much faster because it doesn't run tests at all.

**Comment by dcrissman** [comment]
> The java7 build is much faster because it doesn't run tests at all.

That is correct. We do this because the upstream integration tests require jdk8.

**Comment by paterczm** [comment]
Took a lot of try and error in travis, but I think I finally got it.

**Pull request merged**
